### PR TITLE
add ldap_maps hash

### PR DESCRIPTION
**Pull request by oasys**
Updated PR allowing per-group maps

### CODE REVIEW

**Comment by t0xicCode** [comment]
Would it be possible to update your patch so that when `a` is a Hash, use your code, but when it's a string, do it like previously?

And use a more descriptive variable name than `a`?

Thanks

**Comment by oasys** [comment]
Great idea; will do.  No problem with the style recommendation.

**Comment by oasys** [comment]
I coded it up, but during testing realized that (the ldap_maps portion of) #10 may not work as expected.

From nslcd.conf(5):
```
       map MAP ATTRIBUTE NEWATTRIBUTE
              This option allows for custom attributes to be looked up instead of the default RFC 2307 attributes.   The  MAP
              may  be  one  of  the  supported  maps below.  The ATTRIBUTE is the one as used in RFC 2307 (e.g. userPassword,
              ipProtocolNumber, macAddress, etc.).  The NEWATTRIBUTE may be any attribute as it is available  in  the  direc-
              tory.
```

The MAP attribute isn't optional, as I had surmised from reading #10.  The only way I see it would work is to have hiera data something like:

```
nslcd::ldap_maps:
  passwd:   "uid sAMAccountName"
```

I certainly prefer having a hash, such as:

```
nslcd::ldap_maps:
  passwd:
    uid:                      sAMAccountName
```

especially, since the new attribute could be listed an an expression which would further complicate quoting.

If you agree, and would be willing to accept the PR (code-wise) as stands, let me know and I'll update with new variable names.  Would you prefer ```@ldap_maps.each do |map,attributes|```?

**Comment by oasys** [comment]
Updated PR with proposed variable name.  Also added a sort for the hash keys.  Happy to squash commits if you prefer, just ask.

Thanks for considering this!

**Comment by t0xicCode** [comment]
I'll commit as soon as I get a second.

Thanks

**Comment by hdep** [comment]
Hi @t0xicCode is this repository still under support ? 
Seems not be to be the case as last commit is from 2016. 

Thank you.

**Comment by t0xicCode** [comment]
It may be, but I left the organisation that currently owns the repository
around that time. You may want to see with them about taking the project if
you're interested.

**Comment by geekix** [comment]
@hdep Hi, from what I read in the PR history and code, it should work as expected but I will quickly test it before merging it

**Comment by cabrinha** [comment]
@geekix let's merge this

**Comment by geekix** [comment]
> 
> 
> @geekix let's merge this

Will do, I'll prepare a new version to be released on the puppet forge

**Pull request merged**
