### PR TITLE
Improve the class parameters and switch to proper containment

### PR DESCRIPTION
**Pull request by natemccurdy**
This PR bundles up a few improvements that I noticed could be made:
* The deprecated `validate_` functions have been replaced with parameter data types.
* Static parameter defaults have been moved from params.pp to init.pp. This makes it easier to see at a glance what a parameter's value will be without having to flip to a different file. The params class should really only be used to calculate things.
* Updates the containment from the deprecated anchor pattern to using the [`contain` function](https://puppet.com/docs/puppet/6.3/lang_containment.html#the-contain-function).
* Minor whitespace inconsistency in metadata.json.

### CODE REVIEW

**Comment by geekix** [comment]
Hello,

Thanks for the PR. For my comprehension, why move all default parameters to the init.pp file instead of params.pp ? Is it a best practice ?

**Comment by geekix** [comment]
@natemccurdy thanks for the great work on this, I will release on new module version tomorrow.

**Comment by natemccurdy** [comment]
@geekix Hi, thanks for reviewing and merging!

Regarding the static defaults in init.pp vs. params.pp:

That is a practice that I and others in the community have been moving to. It makes it easier and quicker for folks to see what a default value will be when they don't have to change to a different file.

It also helps to answer the question "is this default value going to change based on some factor"? Putting only the calculated values in params.pp, it signals to the user that only these values could change while the others will more than likely stay static.

It's also a pre-cursor to eventually moving to Hiera 5's module-level data if desired. The values in params.pp will be moved to OS-specific hierarchies and the values in init.pp could stay there or be moved to the common layer of the hierarchy.

**Comment by geekix** [comment]
@natemccurdy thanks for the explanation, it makes sense. I have already release a new module version on the forge with your changes.

**Pull request merged**
